name: Build and Deploy cowsay on DockerHub

on:
  workflow_dispatch:
  push:
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23'

      - name: Command
        run: |
          go mod init cow.go
          go mod tidy
          go build
          ./cow.go

