---
name: Build and Deploy cowsay on DockerHub

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: 'Choose a tag'
        required: true
  push:
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23'

      - name: Command
        run: |
          go mod init cow.go
          go mod tidy
          go build

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            kuza83/CowGO

      - name: log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push on dockerhub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true          
          tags: ${{ steps.meta.outputs.tags }}_${{github.event.inpus.name}}
          labels: ${{ steps.meta.outputs.labels }}
      




